name: solar

on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  push:
    branches:
      - main
      - master

    paths-ignore:
      - '*.m3u'
      - '*.m3u8'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-22.04

    steps:
      - name: 1.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 2.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3.
        run: |
          python -m pip install --upgrade pip
          pip install requests cloudscraper

      - name: 4.
        run: |
          python imach.py

      - name: 5.
        run: |
          git config --local user.email "b-yansh[bot]@users.noreply.github.com"
          git config --local user.name "b-yansh"
          git add imach.pl README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-up: $(TZ='Asia/Jakarta' date +'%Y-%m-%d %H:%M:%S WIB')" && git push)
