name: solar

on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  push:
    branches:
      - main
      - master

    paths-ignore:
      - '*.m3u'
      - '*.m3u8'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bhns0:
    runs-on: ubuntu-22.04

    steps:
      - name: 1.
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 2.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3.
        run: |
          python -m pip install --upgrade pip
          pip install requests cloudscraper

      - name: 4.
        run: |
          echo "${{ secrets.IMACH_PY }}" | base64 -d > imach.py

      - name: 5.
        run: |
          python imach.py

      - name: 6.
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "b-yansh[bot]@users.noreply.github.com"
          git config --local user.name "b-yansh"
          git add a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/imach.pl a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-up: $(TZ='Asia/Jakarta' date +'%Y-%m-%d %H:%M:%S WIB')"

          # 👉 retry push pakai GH_TOKEN
          for i in 1 2 3 4 5; do
            git pull --rebase --autostash origin main
            git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git main && break
            echo "Push gagal, retry ke-$i..."
            sleep 5
          done
          
